apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.stsName }}
spec:
  selector:
    matchLabels:
      data-db: {{ .Values.stsName }}
  serviceName: ""
  replicas: {{ .Values.Statefulset.replicas }}
  template:
    metadata:
      labels:
        data-db: {{ .Values.stsName }}
    spec:
      containers:
        - name: {{ .Values.stsName }}
          image: postgres:{{ .Values.Statefulset.imageTag }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: pgconfigmap
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key:  POSTGRES_PASSWORD 
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ .Values.volumeName }}
              subPath: postgres
      restartPolicy: {{ .Values.Statefulset.restartPolicy }}
      volumes:
        - name: {{ .Values.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.volumeName }}
