apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresService.name }}
  labels:
    data-db: {{ .Values.stsName }}
spec:
  ports:
    - name: {{ .Values.postgresService.portName }}
      port: 5432
      targetPort: 5432
  clusterIP: None
  selector:
    data-db: {{ .Values.stsName }}