apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisService.name}}
  labels:
    data-db: {{ .Values.redisName }}
spec:
  ports:
    - name: {{ .Values.redisService.ports.name }}
      port: 6379
      targetPort: 6379
  clusterIP: None
  selector:
    data-db: {{ .Values.redisName }}