apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    redis-db:  {{ .Values.redisVname }}
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
